COMPILE_DEPS = CORE_DEPS + [
    '@openflowj//jar',
    '@sdnwise//jar',
    '//protocols/sdnwise/api:onos-protocols-sdnwise-api',
    '//protocols/sdnwise/protocol:onos-protocols-sdnwise-protocol',
]

osgi_jar_with_tests (
    deps = COMPILE_DEPS,
)